#!/usr/bin/env python3


class Condiction:
    def __init__(self, condiction, symbols = []):
        self.condiction =  condiction
        self.symbols = symbols

    def __str__(self):
         return "${self.codiction}    { ${self.symbols} }\n"

class Exp:
    def __init__(self, name, condictions):
        self.name = name
        self.condictions =  condictions

    def __str__(self):
        phrase = self.name + "-> "
        first = True
        for name in self.condictions:
            if first:
                phrase = phrase + name + "\n"
                first = False
            else:
                phrase = phrase + "    | " + name + "\n"
        return phrase

class LL1:
    def __init__(self, exps = {}):
        self.exps = exps

    def __str__(self):
         return "${self.exps}"
